version: '3.7'

services:

  postgres:
    container_name: 'examples.postgres'
    restart: always
    image: postgres
    build:
      context: ./
      dockerfile: postgres.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - /usr/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=exampledb
    networks:
      - razornetwork

  
  app:
    container_name: 'movies.app'
    build:
      context: ../
      dockerfile: movies.dockerfile
    ports:
      - "5000:5000"
    networks:
      - razornetwork

  razor:
    container_name: 'movies.razor'
    build:
      context: ../
      dockerfile: razor.dockerfile
    ports:
      - "80:80"
    networks:
      - razornetwork

networks:
  razornetwork:
    driver: bridge
    external: true
