version: '3.4'

services:
  
  
  movieswebapplication:
    image: ${DOCKER_REGISTRY-}movieswebapplication
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:80
    networks:
      - internal

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /usr/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - internal

networks:
  internal:
    driver: bridge
