// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesWebApplication.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MoviesWebApplication.Migrations
{
    [DbContext(typeof(MoviesDBContext))]
    [Migration("20201222201215_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MoviesWebApplication.Models.Movies", b =>
                {
                    b.Property<int>("MoviesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("MoviesId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MoviesId = 1,
                            Name = "First Title",
                            Year = 1990
                        },
                        new
                        {
                            MoviesId = 2,
                            Name = "Second Title",
                            Year = 2000
                        },
                        new
                        {
                            MoviesId = 3,
                            Name = "Third Title",
                            Year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
